# Generated by Django 4.0.3 on 2022-05-10 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('country', models.CharField(max_length=200, null=True)),
                ('is_dead', models.BooleanField()),
                ('a', models.CharField(max_length=200, null=True)),
                ('ns', models.CharField(max_length=200, null=True)),
                ('cname', models.CharField(max_length=200, null=True)),
                ('mx', models.CharField(max_length=200, null=True)),
                ('txt', models.CharField(max_length=200, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.url')),
            ],
        ),
    ]
