# Generated by Django 4.0.4 on 2022-05-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200)),
                ('link', models.CharField(default='', max_length=2083)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('country', models.CharField(max_length=200)),
                ('is_dead', models.BooleanField()),
                ('a', models.CharField(max_length=200)),
                ('ns', models.CharField(max_length=200)),
                ('cname', models.CharField(max_length=200)),
                ('mx', models.CharField(max_length=200)),
                ('txt', models.CharField(max_length=200)),
            ],
        ),
    ]
