# Generated by Django 4.0.3 on 2022-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='a',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='cname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='mx',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='ns',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='txt',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
